{
    'name': 'Solutions2use Warehouse',
    'author': 'Solutions2use',
    'license': 'AGPL-3',
    'website': 'https://www.solutions2use.com',
    'version': '0.1',
    'summary': 'Solutions2use Warehousing',
    'category':  'Warehousing',
    'images': ['static/description/icon.png'],
    'description':
        """
        """,
    'depends': ['base_setup', 's2ubase', 's2ucrm', 's2ubaseproduct', 's2uaccount'],
    'data': [
        # security
        'security/rules.xml',
        'security/ir.model.access.csv',
        'security/res_groups.xml',
        # views
        'views/menus.xml',
        'views/pallet_view.xml',
        'views/shipment_view.xml',
        'views/location_view.xml',
        'views/unit_view.xml',
        'views/move_view.xml',
        'views/production_view.xml',
        'views/uom_view.xml',
        'views/available_view.xml',
        'views/serialnumber_view.xml',
        'views_inherited/entity_view.xml',
        'wizards/views/confirm_and_pick.xml',
        'output/reports.xml',
        'output/templates/print_unit_card.xml',
        'output/templates/print_outgoing_card.xml',
        'output/templates/print_inventory_product.xml',
        'reports/views/inventory_product.xml',
        'output/templates/print_inventory_location.xml',
        'reports/views/inventory_location.xml',
        'output/templates/print_pallets_saldo.xml',
        'reports/views/pallets_saldo.xml',
        'output/templates/print_pallets_history.xml',
        'reports/views/pallets_history.xml',
        'output/templates/print_delivery.xml',
        'output/templates/print_rma.xml',
    ],
    'installable': True,
    'auto_install': False,
}
